In [28]:
import warnings
warnings.filterwarnings('ignore')

In [29]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [30]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [31]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [32]:
# Load the data
file_path = Path('LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

# Split the Data into Training and Testing

In [35]:
# Create our features
X = pd.get_dummies(df.drop(columns=['loan_status']))

# Create our target
y = pd.DataFrame(df['loan_status'])
X.head()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
0,10500.0,0.1719,375.35,66000.0,27.24,0.0,0.0,8.0,0.0,1609.0,...,1,1,0,1,0,1,1,0,1,1
1,25000.0,0.2000,929.09,105000.0,20.23,0.0,0.0,17.0,1.0,18368.0,...,1,1,0,1,0,1,1,0,1,1
2,20000.0,0.2000,529.88,56000.0,24.26,0.0,0.0,8.0,0.0,13247.0,...,1,1,0,1,0,1,1,0,1,1
3,10000.0,0.1640,353.55,92000.0,31.44,0.0,1.0,10.0,1.0,17996.0,...,1,1,0,1,0,1,1,0,1,1
4,22000.0,0.1474,520.39,52000.0,18.76,0.0,1.0,14.0,0.0,9091.0,...,1,1,0,1,0,1,1,0,1,1

In [36]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.177238,1.0,0.123879,0.876121,0.383161,0.616839,0.860340,0.139660,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.381873,0.0,0.329446,0.329446,0.486161,0.486161,0.346637,0.346637,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,0.000000,1.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0

In [37]:
# Check the balance of our target values
y['loan_status'].value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=82, stratify=y)

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [39]:
# Resample the training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier
balranfor = BalancedRandomForestClassifier(n_estimators=100, random_state=66)
balranfor.fit(X_train, y_train)

BalancedRandomForestClassifier(random_state=66)

In [40]:
# Calculated the balanced accuracy score
y_pred = balranfor.predict(X_test)

In [41]:
# Display the confusion matrix
conf = confusion_matrix(y_test, y_pred)
conf_df = pd.DataFrame(
    conf, index=["Actual high", "Actual low"], columns=["Predicted high", "Predicted low"])
conf_df

             Predicted high  Predicted low
Actual high              56             31
Actual low             1961          15157

In [42]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.03      0.64      0.89      0.05      0.75      0.56        87
   low_risk       1.00      0.89      0.64      0.94      0.75      0.58     17118

avg / total       0.99      0.88      0.64      0.93      0.75      0.58     17205

In [43]:
# List the features sorted in descending order by feature importance
feature_importance_rank = sorted(zip(balranfor.feature_importances_, X.columns), reverse=True)
for feature in feature_importance_rank:
    print(f"{feature[1]}: ({feature[0]})")

total_rec_prncp: (0.06991373770759617)
last_pymnt_amnt: (0.06729297658000429)
total_pymnt_inv: (0.06116435146024087)
total_rec_int: (0.053581249405484296)
total_pymnt: (0.052077556114691156)
issue_d_Jan-2019: (0.022196003067363065)
int_rate: (0.0211086393511037)
installment: (0.020509413973303935)
out_prncp: (0.017682237590703476)
mo_sin_old_rev_tl_op: (0.017508178950469456)
annual_inc: (0.01699484683196437)
total_bal_il: (0.015979299150232277)
max_bal_bc: (0.01588564045281979)
out_prncp_inv: (0.01549088761354589)
dti: (0.01535818783298849)
total_bc_limit: (0.015258869988992597)
tot_cur_bal: (0.015148918727755653)
avg_cur_bal: (0.014876566044319577)
mo_sin_old_il_acct: (0.014646299067566588)
mths_since_recent_inq: (0.013961706982118354)
bc_open_to_buy: (0.013780833508136305)
total_bal_ex_mort: (0.013522407142532882)
tot_hi_cred_lim: (0.01332287656150151)
revol_bal: (0.01296316445174557)
total_rev_hi_lim: (0.012946490283471052)
mths_since_recent_bc: (0.012916210666247178)
all_util: (0.012872246648049711)
bc_util: (0.012798539309647791)
total_il_high_credit_limit: (0.012689549569026203)
issue_d_Mar-2019: (0.012444058794411895)
il_util: (0.012193231124211968)
loan_amnt: (0.012014039822145042)
total_acc: (0.01163216477259629)
num_sats: (0.011328054962784138)
mo_sin_rcnt_rev_tl_op: (0.010813142635478763)
mths_since_rcnt_il: (0.010363092173385496)
inq_last_12m: (0.009945216998084193)
pct_tl_nvr_dlq: (0.009851094374506576)
num_il_tl: (0.009443176611567622)
num_rev_tl_bal_gt_0: (0.009403025104114534)
num_op_rev_tl: (0.0089132392079515)
num_bc_sats: (0.008895202352311206)
mort_acc: (0.008849739058020861)
num_actv_rev_tl: (0.008690772960099536)
num_tl_op_past_12m: (0.008455277223981348)
open_rv_24m: (0.008237196544109975)
mo_sin_rcnt_tl: (0.008209167930788908)
num_rev_accts: (0.008136183897181017)
issue_d_Feb-2019: (0.007479188227554097)
inq_fi: (0.0073590988792070836)
open_acc: (0.007277354999510697)
num_bc_tl: (0.007220465164480733)
acc_open_past_24mths: (0.006701857735354395)
total_rec_late_fee: (0.0066819762818957976)
num_actv_bc_tl: (0.006443384483060196)
percent_bc_gt_75: (0.0062635677845060585)
total_cu_tl: (0.006259003058429875)
open_il_24m: (0.0060832402566938755)
inq_last_6mths: (0.005967822731607811)
next_pymnt_d_May-2019: (0.00575684619880735)
open_acc_6m: (0.005670823395974196)
open_act_il: (0.005640071902638311)
delinq_2yrs: (0.005525074201783724)
open_rv_12m: (0.005232232101634137)
next_pymnt_d_Apr-2019: (0.004908003438275524)
open_il_12m: (0.0035212880022510397)
tot_coll_amt: (0.0030537374770423535)
verification_status_Source Verified: (0.002612554929330936)
home_ownership_MORTGAGE: (0.0025182348168098397)
num_accts_ever_120_pd: (0.0023536942083490185)
application_type_Individual: (0.0020906053171236504)
verification_status_Verified: (0.001952043024386204)
home_ownership_RENT: (0.0019319652553365868)
home_ownership_OWN: (0.0016981142594631403)
pub_rec_bankruptcies: (0.0016907715341404259)
verification_status_Not Verified: (0.0015693668069309463)
initial_list_status_f: (0.001377994225003465)
application_type_Joint App: (0.0013114936785295031)
pub_rec: (0.0012147396487636774)
initial_list_status_w: (0.0012134585578833922)
num_tl_90g_dpd_24m: (0.0009440755186970796)
collections_12_mths_ex_med: (0.0001202283791605158)
home_ownership_ANY: (9.066193803124345e-05)
tax_liens: (0.0)
recoveries: (0.0)
pymnt_plan_n: (0.0)
policy_code: (0.0)
num_tl_30dpd: (0.0)
num_tl_120dpd_2m: (0.0)
hardship_flag_N: (0.0)
delinq_amnt: (0.0)
debt_settlement_flag_N: (0.0)
collection_recovery_fee: (0.0)
chargeoff_within_12_mths: (0.0)
acc_now_delinq: (0.0)

### Easy Ensemble AdaBoost Classifier

In [44]:
# Train the EasyEnsembleClassifier
from imblearn.ensemble import EasyEnsembleClassifier
ezez = EasyEnsembleClassifier(n_estimators=100, random_state=20)
ezez.fit(X_train, y_train)

EasyEnsembleClassifier(n_estimators=100, random_state=20)

In [45]:
# Calculated the balanced accuracy score
y_pred = ezez.predict(X_test)

In [46]:
# Display the confusion matrix
conf = confusion_matrix(y_test, y_pred)
conf_df = pd.DataFrame(
    conf, index=["Actual high", "Actual low"], columns=["Predicted high", "Predicted low"])
conf_df

             Predicted high  Predicted low
Actual high              74             13
Actual low              932          16186

In [47]:
# Print the imbalanced classification report
classification_report_imbalanced(y_test, y_pred)

'                   pre       rec       spe        f1       geo       iba       sup\n\n  high_risk       0.07      0.85      0.95      0.14      0.90      0.80        87\n   low_risk       1.00      0.95      0.85      0.97      0.90      0.81     17118\n\navg / total       0.99      0.95      0.85      0.97      0.90      0.81     17205\n'